/*
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractFsmScopeProvider extends XtypeScopeProvider {
}
