/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import polymorphic.csv.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CsvFactoryImpl extends EFactoryImpl implements CsvFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CsvFactory init()
  {
    try
    {
      CsvFactory theCsvFactory = (CsvFactory)EPackage.Registry.INSTANCE.getEFactory(CsvPackage.eNS_URI);
      if (theCsvFactory != null)
      {
        return theCsvFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CsvFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CsvFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CsvPackage.MODEL: return createModel();
      case CsvPackage.LANGUAGE: return createLanguage();
      case CsvPackage.ACTION: return createAction();
      case CsvPackage.OPEN_CSV: return createOpenCSV();
      case CsvPackage.REF_OPEN_ACTION: return createRefOpenAction();
      case CsvPackage.PRINT_CSV: return createPrintCSV();
      case CsvPackage.NB_ROW: return createNbRow();
      case CsvPackage.NB_COL: return createNbCol();
      case CsvPackage.SAVE_CSV: return createSaveCSV();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Language createLanguage()
  {
    LanguageImpl language = new LanguageImpl();
    return language;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Action createAction()
  {
    ActionImpl action = new ActionImpl();
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OpenCSV createOpenCSV()
  {
    OpenCSVImpl openCSV = new OpenCSVImpl();
    return openCSV;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RefOpenAction createRefOpenAction()
  {
    RefOpenActionImpl refOpenAction = new RefOpenActionImpl();
    return refOpenAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PrintCSV createPrintCSV()
  {
    PrintCSVImpl printCSV = new PrintCSVImpl();
    return printCSV;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NbRow createNbRow()
  {
    NbRowImpl nbRow = new NbRowImpl();
    return nbRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NbCol createNbCol()
  {
    NbColImpl nbCol = new NbColImpl();
    return nbCol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SaveCSV createSaveCSV()
  {
    SaveCSVImpl saveCSV = new SaveCSVImpl();
    return saveCSV;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CsvPackage getCsvPackage()
  {
    return (CsvPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CsvPackage getPackage()
  {
    return CsvPackage.eINSTANCE;
  }

} //CsvFactoryImpl
