/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv.impl;

import org.eclipse.emf.ecore.EClass;

import polymorphic.csv.CsvPackage;
import polymorphic.csv.NbCol;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nb Col</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NbColImpl extends RefOpenActionImpl implements NbCol
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NbColImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvPackage.Literals.NB_COL;
  }

} //NbColImpl
