/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv.impl;

import org.eclipse.emf.ecore.EClass;

import polymorphic.csv.CsvPackage;
import polymorphic.csv.NbRow;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nb Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NbRowImpl extends RefOpenActionImpl implements NbRow
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NbRowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvPackage.Literals.NB_ROW;
  }

} //NbRowImpl
