/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv.impl;

import org.eclipse.emf.ecore.EClass;

import polymorphic.csv.CsvPackage;
import polymorphic.csv.PrintCSV;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintCSVImpl extends RefOpenActionImpl implements PrintCSV
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintCSVImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvPackage.Literals.PRINT_CSV;
  }

} //PrintCSVImpl
