/**
 * generated by Xtext 2.13.0
 */
package polymorphic.csv.impl;

import org.eclipse.emf.ecore.EClass;

import polymorphic.csv.CsvPackage;
import polymorphic.csv.SaveCSV;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Save CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SaveCSVImpl extends ActionsImpl implements SaveCSV
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SaveCSVImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvPackage.Literals.SAVE_CSV;
  }

} //SaveCSVImpl
