/*
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import polymorphic.fsm.fsm.Machine

@RunWith(XtextRunner)
@InjectWith(FsmInjectorProvider)
class FsmParsingTest {
	@Inject
	ParseHelper<Machine> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
