/*
 * generated by Xtext 2.13.0
 */
package polymorphic.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractCsvScopeProvider extends XtypeScopeProvider {
}
