/*
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import polymorphic.fsm.ui.internal.FsmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FsmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FsmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FsmActivator activator = FsmActivator.getInstance();
		return activator != null ? activator.getInjector(FsmActivator.POLYMORPHIC_FSM_FSM) : null;
	}

}
