/*
 * generated by Xtext 2.13.0
 */
package polymorphic.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import polymorphic.csv.ui.internal.CsvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CsvExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CsvActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CsvActivator activator = CsvActivator.getInstance();
		return activator != null ? activator.getInjector(CsvActivator.POLYMORPHIC_CSV) : null;
	}

}
