/**
 * generated by Xtext 2.13.0
 */
package polymorphic.ui.contentassist;

import polymorphic.ui.contentassist.AbstractCsvProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CsvProposalProvider extends AbstractCsvProposalProvider {
}
