/*
 * generated by Xtext 2.12.0
 */
package polymorphic.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import polymorphic.csv.ui.internal.CsvActivator;

public class CsvUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CsvActivator.getInstance().getInjector("polymorphic.Csv");
	}

}
