/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.ide;

import polymorphic.fsm.ide.AbstractFsmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FsmIdeModule extends AbstractFsmIdeModule {
}
