/**
 * generated by Xtext 2.13.0
 */
package polymorphic.ide;

import polymorphic.ide.AbstractCsvIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CsvIdeModule extends AbstractCsvIdeModule {
}
