/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.ui.contentassist;

import java.util.function.BiConsumer;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import polymorphic.fsm.generator.GeneratorCollection;
import polymorphic.fsm.generator.fsm.IFsmGenerator;
import polymorphic.fsm.ui.contentassist.AbstractFsmProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FsmProposalProvider extends AbstractFsmProposalProvider {
  private final GeneratorCollection generators = new GeneratorCollection();
  
  @Override
  public void completeLanguage_Name(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    super.completeLanguage_Name(model, assignment, context, acceptor);
    final BiConsumer<String, IFsmGenerator> _function = (String p1, IFsmGenerator p2) -> {
      acceptor.accept(this.createCompletionProposal(p1, context));
    };
    this.generators.getMap().forEach(_function);
  }
}
