grammar polymorphic.Csv with org.eclipse.xtext.xbase.Xtype

generate csv "http://www.Csv.polymorphic"

Model:
	{Model}
	'constraints' '{'
	constraints+=Constraint*
	'}'
	'languages' '{'
	languages+=Language*
	'}'
	(actions+=Actions)*;

Constraint:
	name=ID '=' (true?='true' | 'false');

Language:
	name=ID '(' target=QualifiedName ')';

Actions:
	{OpenCSV} 'read' name=ID file=STRING |
	{PrintCSV} 'print' name=ID |
	{SaveCSV} 'save' name=ID (file=STRING)?;