/*
 * generated by Xtext 2.13.0
 */
package polymorphic


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CsvStandaloneSetup extends CsvStandaloneSetupGenerated {

	def static void doSetup() {
		new CsvStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
