/*
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import polymorphic.fsm.ui.internal.FsmActivator;

public class FsmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FsmActivator.getInstance().getInjector("polymorphic.fsm.Fsm");
	}

}
