/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see polymorphic.csv.CsvPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
} // Action
