/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nb Col</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see polymorphic.csv.CsvPackage#getNbCol()
 * @model
 * @generated
 */
public interface NbCol extends RefOpenAction
{
} // NbCol
