/**
 * generated by Xtext 2.12.0
 */
package polymorphic.csv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see polymorphic.csv.CsvPackage#getPrintCSV()
 * @model
 * @generated
 */
public interface PrintCSV extends Actions
{
} // PrintCSV
