/**
 * generated by Xtext 2.13.0
 */
package polymorphic.csv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Open Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link polymorphic.csv.RefOpenAction#getOpen <em>Open</em>}</li>
 * </ul>
 *
 * @see polymorphic.csv.CsvPackage#getRefOpenAction()
 * @model
 * @generated
 */
public interface RefOpenAction extends Action
{
  /**
   * Returns the value of the '<em><b>Open</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Open</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open</em>' reference.
   * @see #setOpen(OpenCSV)
   * @see polymorphic.csv.CsvPackage#getRefOpenAction_Open()
   * @model
   * @generated
   */
  OpenCSV getOpen();

  /**
   * Sets the value of the '{@link polymorphic.csv.RefOpenAction#getOpen <em>Open</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Open</em>' reference.
   * @see #getOpen()
   * @generated
   */
  void setOpen(OpenCSV value);

} // RefOpenAction
