/**
 * generated by Xtext 2.13.0
 */
package polymorphic.csv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Save CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see polymorphic.csv.CsvPackage#getSaveCSV()
 * @model
 * @generated
 */
public interface SaveCSV extends Actions
{
} // SaveCSV
