/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import polymorphic.fsm.ui.AbstractFsmUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FsmUiModule extends AbstractFsmUiModule {
  public FsmUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
