/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.fsm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link polymorphic.fsm.fsm.Model#getName <em>Name</em>}</li>
 *   <li>{@link polymorphic.fsm.fsm.Model#getConstraints <em>Constraints</em>}</li>
 *   <li>{@link polymorphic.fsm.fsm.Model#getLanguages <em>Languages</em>}</li>
 *   <li>{@link polymorphic.fsm.fsm.Model#getMachine <em>Machine</em>}</li>
 * </ul>
 *
 * @see polymorphic.fsm.fsm.FsmPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see polymorphic.fsm.fsm.FsmPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link polymorphic.fsm.fsm.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link polymorphic.fsm.fsm.Constraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see polymorphic.fsm.fsm.FsmPackage#getModel_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getConstraints();

  /**
   * Returns the value of the '<em><b>Languages</b></em>' containment reference list.
   * The list contents are of type {@link polymorphic.fsm.fsm.Language}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Languages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Languages</em>' containment reference list.
   * @see polymorphic.fsm.fsm.FsmPackage#getModel_Languages()
   * @model containment="true"
   * @generated
   */
  EList<Language> getLanguages();

  /**
   * Returns the value of the '<em><b>Machine</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machine</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machine</em>' containment reference.
   * @see #setMachine(Machine)
   * @see polymorphic.fsm.fsm.FsmPackage#getModel_Machine()
   * @model containment="true"
   * @generated
   */
  Machine getMachine();

  /**
   * Sets the value of the '{@link polymorphic.fsm.fsm.Model#getMachine <em>Machine</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Machine</em>' containment reference.
   * @see #getMachine()
   * @generated
   */
  void setMachine(Machine value);

} // Model
