/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm.fsm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link polymorphic.fsm.fsm.Transition#getFrom <em>From</em>}</li>
 *   <li>{@link polymorphic.fsm.fsm.Transition#getTo <em>To</em>}</li>
 *   <li>{@link polymorphic.fsm.fsm.Transition#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see polymorphic.fsm.fsm.FsmPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(State)
   * @see polymorphic.fsm.fsm.FsmPackage#getTransition_From()
   * @model
   * @generated
   */
  State getFrom();

  /**
   * Sets the value of the '{@link polymorphic.fsm.fsm.Transition#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(State value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(State)
   * @see polymorphic.fsm.fsm.FsmPackage#getTransition_To()
   * @model
   * @generated
   */
  State getTo();

  /**
   * Sets the value of the '{@link polymorphic.fsm.fsm.Transition#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(State value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' attribute.
   * @see #setEvent(String)
   * @see polymorphic.fsm.fsm.FsmPackage#getTransition_Event()
   * @model
   * @generated
   */
  String getEvent();

  /**
   * Sets the value of the '{@link polymorphic.fsm.fsm.Transition#getEvent <em>Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' attribute.
   * @see #getEvent()
   * @generated
   */
  void setEvent(String value);

} // Transition
