/*
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FsmRuntimeModule extends AbstractFsmRuntimeModule {
}
