/*
 * generated by Xtext 2.13.0
 */
package polymorphic.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class CsvWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public CsvWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
