/**
 * generated by Xtext 2.13.0
 */
package polymorphic.validation;

import polymorphic.validation.AbstractCsvValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CsvValidator extends AbstractCsvValidator {
}
