/**
 * generated by Xtext 2.13.0
 */
package polymorphic;

import polymorphic.AbstractCsvRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvRuntimeModule extends AbstractCsvRuntimeModule {
}
