/**
 * generated by Xtext 2.13.0
 */
package polymorphic;

import polymorphic.CsvStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvStandaloneSetup extends CsvStandaloneSetupGenerated {
  public static void doSetup() {
    new CsvStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
