/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm;

import polymorphic.fsm.AbstractFsmRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmRuntimeModule extends AbstractFsmRuntimeModule {
}
