/**
 * generated by Xtext 2.13.0
 */
package polymorphic.fsm;

import polymorphic.fsm.FsmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmStandaloneSetup extends FsmStandaloneSetupGenerated {
  public static void doSetup() {
    new FsmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
